{{- range $name, $value := .Values.microService}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "xinlus.fullname" $) $name }}
  labels:
    {{- include "xinlus.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  {{- if not $value.servicePort }}
  clusterIP: None
  {{- end }}
  ports:
    - name: http
      protocol: TCP
      {{- if $value.servicePort }}
      port: {{ $value.servicePort }}
      targetPort:  {{ $value.containerPort }}
      {{- else }}
      port: {{ $value.containerPort }}
      {{- end }}
  selector:
    {{- include "xinlus.selectorLabels" $ | nindent 4 }}
    app: {{ printf "%s-%s" (include "xinlus.fullname" $) $name }}
---
{{- end }}