apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "xinlus.fullname" $) "springcloud" }}
  labels:
    {{- include "xinlus.labels" . | nindent 4 }}
    app: {{ printf "%s-%s" (include "xinlus.fullname" $) "springcloud" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "xinlus.selectorLabels" . | nindent 6 }}
      app: {{ printf "%s-%s" (include "xinlus.fullname" $) "springcloud" }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xinlus.selectorLabels" . | nindent 8 }}
        app: {{ printf "%s-%s" (include "xinlus.fullname" $) "springcloud" }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xinlus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- range $name, $value := .Values.springcloud }}
        - name: {{ printf "%s-%s" $.Chart.Name  $name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- if .image.tag }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- else }}
          {{ $tags := $.Files.Get "tags.yaml" | toString | fromYaml }}
          {{- if and $tags (index $tags .image.repository) }}
          image: {{ printf "%s:%s" .image.repository (index $tags .image.repository ) | quote}}
          {{- else }}
          image: "{{ .image.repository }}"
          {{- end }}
          {{- end }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: SERVER_PORT
              value: {{ $value.containerPort | quote }}
            {{- if $value.injectNacosEnv }}
            - name: NACOS_HOSTNAME
              value: {{ include "xinlus.registerServerName" $ | quote }}
            - name: NACOS_PORT
              value: {{ include "xinlus.registerServerPort" $ | quote }}
            {{- end }}
            {{- with $value.environments }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $value.containerPort }}
              protocol: TCP
            - name: client-rpc
              containerPort: 9848
              protocol: TCP
            - name: client-grpc
              containerPort: 9849
              protocol: TCP
          resources:
          {{- if $value.resources }}
            {{- toYaml $value.resources | nindent 12 }}
          {{- else if $value.resourcesType }}
            {{- toYaml (index $.Values.resources $value.resourcesType) | nindent 12 }}
          {{- else }}
            {{- toYaml $.Values.resources.default | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
